version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - analytix-frontend
      - analytix-backend
    networks:
      - app_network
    restart: always

  analytix-backend:
    build: ./analytix-backend
    container_name: analytix-backend
    expose:
      - "8080"
    networks:
      - app_network
    restart: always

  analytix-frontend:
    build: ./analytix-frontend
    container_name: analytix-frontend
    expose:
      - "3000"
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
